### PR TITLE
Dev/47 without login return the login screen

### LINKED ISSUE #47: Security: without login every route should return the login screen.
**Describe the bug**
When replacing /Login with /index the user is not being stopped and visit this page without credentials.
This could be a security risk!

**To Reproduce**
1. Go to `localhost:8080\index`
4. See that the user is now on `localhost:8080\index` without being logged in.

**Expected behavior**
User should be redirected to `localhost:8080\Login` when not logged in with correct credentials.

**Desktop (please complete the following information):**
 - OS: W11
 - Browser FireFox-144

**Additional context**
This is browser and OS independent.

### PR DESCRIPTION
**Pull request by SociopathicPixel**

### CODE REVIEW

File: printlib-backend/src/main/java/nl/pixel/printlib/config/JwtUtil.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        } catch (JWTVerificationException e) {
+            return false;
+        }
+    }
+
+    public String extractUsername(String token) {
+        DecodedJWT jwt = JWT.decode(token);
+        return jwt.getSubject();
+    }
+}
```
Comment (SociopathicPixel) [inline printlib-backend/src/main/java/nl/pixel/printlib/config/JwtUtil.java]: add newline to EOF

File: printlib-backend/src/main/java/nl/pixel/printlib/config/SecurityConfig.java [hunk 2]
```diff
@@ -18,15 +18,26 @@ public PasswordEncoder passwordEncoder(){
     }
 
     @Bean
-    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
+    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
         http
-                .csrf(AbstractHttpConfigurer::disable)
-                .authorizeHttpRequests(auth -> auth
-                        .requestMatchers("/api/auth/**").permitAll()
```
Comment (SociopathicPixel) [inline printlib-backend/src/main/java/nl/pixel/printlib/config/SecurityConfig.java:25]: Keep this, its cleaner than having every auth call listed.
We will assume that every api call with "auth" should be open to the outside for validation.

File: printlib-backend/src/main/java/nl/pixel/printlib/config/SecurityConfig.java [hunk 3]
```diff
@@ -18,15 +18,26 @@ public PasswordEncoder passwordEncoder(){
...
-                        .anyRequest().authenticated()
+                .authorizeHttpRequests(authorizeRequests -> authorizeRequests
+                        .requestMatchers("/api/auth/login").permitAll()
+                        .requestMatchers("/api/auth/register").permitAll()
```
Comment (SociopathicPixel) [inline printlib-backend/src/main/java/nl/pixel/printlib/config/SecurityConfig.java]: remove these two lines according to previous review comment

File: printlib-backend/src/main/java/nl/pixel/printlib/web/auth/payload/LoginResponse.java [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+@Setter
+@Getter
+public class LoginResponse {
+    private String token;
+
+    public LoginResponse(String token) {
+        this.token = token;
+    }
+
+}
```
Comment (SociopathicPixel) [inline printlib-backend/src/main/java/nl/pixel/printlib/web/auth/payload/LoginResponse.java]: add newline to EOF

File: printlib-backend/src/main/java/nl/pixel/printlib/web/auth/service/impl/AuthServiceImpl.java [hunk 5]
```diff
@@ -1,42 +1,62 @@
...
+
     @Override
     public boolean register(User user) {
-        logger.info("Attempting to register user: {}", user.getUsername());
-        if (repository.findByUsername(user.getUsername()).isPresent()) {
-            logger.warn("Registration failed: username '{}' already exists", user.getUsername());
+        try {
+            service.registerUser(user);
+            return true;
+        } catch (UserRegistrationException e) {
```
Comment (SociopathicPixel) [inline printlib-backend/src/main/java/nl/pixel/printlib/web/auth/service/impl/AuthServiceImpl.java:57]: make this a single line: bool ? a : b

File: printlib-backend/src/test/java/nl/pixel/printlib/web/auth/TestAuthRestAPI.java [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+    }
+
+    @Test
+    public void loginPageIsAvailable() throws Exception {
+        mockMvc.perform(get("/api/auth/login"))
+                .andExpect(status().isOk());
+    }
+
+
+}
```
Comment (SociopathicPixel) [inline printlib-backend/src/test/java/nl/pixel/printlib/web/auth/TestAuthRestAPI.java]: add newline to EOF

**Review by SociopathicPixel — COMMENTED** [review]
still some minor things

File: printlib-backend/src/main/java/nl/pixel/printlib/web/auth/service/impl/AuthServiceImpl.java (hunk 5 above)
Comment (SociopathicPixel) [reply printlib-backend/src/main/java/nl/pixel/printlib/web/auth/service/impl/AuthServiceImpl.java:57]: Can't

**Review by SociopathicPixel — COMMENTED** [review]
LGTM
